name: Team approval workflow
on: pull_ewquest_review

jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    step:
      - name: Label approved pull requests
        uses: abinoda/label-when-approved-action@1.0.5
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ADD_LABEL: "AAAAAA"
